### ISSUE TITLE
Routing in apps

### ISSUE THREAD

**Issue by MohammadKoolivand** [ogzhanolguncu/react-typescript-module-federation#12]
As I realize, it doesn't mentioned in this repo how routing can be implemented. Thanks

**Comment by serhatgnc** [comment]
https://github.com/ogzhanolguncu/react-typescript-module-federation/pull/13 this feature has been added.

I'm closing the issue and if you have any questions feel free to add a new issue.

**Comment by MohammadKoolivand** [comment]
> #13 this feature has been added.
> 
> I'm closing the issue and if you have any questions feel free to add a new issue.

Thanks. Well done.

**Comment by MohammadKoolivand** [comment]
Actually I wanted to know how Routing can be implemented in sub-applications. when container and applications have routing, How should be handle this? Thanks

**Comment by MohammadKoolivand** [comment]
> Actually I wanted to know how Routing can be implemented in sub-applications. when container and applications have routing, How should be handle this? Thanks

Actually I wanted to know how Routing can be implemented in sub-applications. when container and applications have routing, How should be handle this? Thanks

**Comment by MohammadKoolivand** [comment]
> #13 this feature has been added.
> 
> I'm closing the issue and if you have any questions feel free to add a new issue.

Actually I wanted to know how Routing can be implemented in sub-applications. when container and applications have routing, How should be handle this? Thanks

**Comment by ogzhanolguncu** [comment]
The same way we did in the container you can setup individual routing in sub-applications. Sub-applications are still SPAs you can treat them as regular React apps.
