### ISSUE TITLE
webpack.prod.js missing

### ISSUE THREAD

**Issue by micronyks** [ogzhanolguncu/react-typescript-module-federation#8]
Hi There,

Let me thank you for making all these repos. It has been helping me to create MFE architecture using react with typescript. I'm able to create MFE with your repos and has progressed well. 

Now, I have to deploy all MFEs to AWS cloud. I have been following your article and repos but somehow `webpack.prod.js` is missing. I need your help to provide the same. That would me a great help for people like me. 

Thanks in advance. Expecting quick response from you.

PS: It would be helpful if you can write or point to an article for deployment to AWS.

Regards,
Nikhil

**Comment by ogzhanolguncu** [comment]
Hey there, I'm really sorry about webpack.prod.js. I'll update the article as soon as I can. And, for the deployment, if you would like to deploy it on AWS S3. You can just copy this [Github Action](https://github.com/ogzhanolguncu/react-typescript-module-federation/blob/master/.github/workflows/s3-deploy.yaml) and place your secrets in the settings of your project and add them hard-coded if your project is private.

You can find the secrets tab in the screenshot below:

![Capture](https://user-images.githubusercontent.com/21091016/159352762-3b856bfd-421f-4363-aff0-73fe3b250cb7.PNG)

**Comment by ogzhanolguncu** [comment]
@micronyks if everything is okay I'm closing the issue?

**Comment by micronyks** [comment]
Thanks a lot for providing the information. Yes you can close it. Thanks again !

**Comment by micronyks** [comment]
@ogzhanolguncu 

Greetings,
Thanks for replying & helping.

I just have one query as below. 

I want to dockerize these micro frontend apps and want to generate dockerized build. After dockerizing it, I just want to give those images to someone and someone should be able to run the docker images and finally he can see these MFE apps running without any setup.

Do you know how to dockerize these MFEs? I tried searching solutions online like docker & webapck but didn't get any help.

Reaching out to you incase if you have already done it or willing to help.

Any help would be highly appreciated.

**Comment by ogzhanolguncu** [comment]
Hey there @micronyks,

There aren't many differences when it comes to dockerizing. All you have to do is dockerize the React app and configure your paths in the Webpack like this:

```javascript
new ModuleFederationPlugin({
        name: "container",
        remotes: {
          app1: isProduction ? process.env.PROD_APP1 : process.env.DEV_APP1,
          app2: isProduction ? process.env.PROD_APP2 : process.env.DEV_APP2,
        }),
```

So, when all your MF apps are deployed it should work just sorry.

By the way, sorry for not being able to provide Dockerfile, but you can use [GithubAction](https://github.com/ogzhanolguncu/react-typescript-module-federation/blob/master/.github/workflows/s3-deploy.yaml) to get a rough idea.
